export { default as Home } from "./Home/Home";
export { default as EpisodesSlider } from "./EpisodesSlider/EpisodesSlider";
export { default as About } from "./About/About";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as SingleEpisodePage } from "./SingleEpisodePage/SingleEpisodePage";
export { default as Episodes } from "./Episodes/Episodes";
export { default as Contact } from "./Contact/Contact";
export { default as Footer } from "./Footer/Footer";
export { default as AboutPage } from "./AboutPage/AboutPage";
